namespace Fun.Blazor

open Fun.Blazor
open Fun.Blazor.Operators
open Microsoft.AspNetCore.Components


type FunBlazorAttrEngine(mk, mkBool) =
    inherit Feliz.AttrEngine<AttrRenderFragment>(mk, mkBool)

    member inline _.ref([<InlineIfLambda>] fn: ElementReference -> unit) =
        AttrRenderFragment(fun _ builder index ->
            builder.AddElementReferenceCapture(index, fn)
            index + 1
        )

    member inline _.childContent(nodes: NodeRenderFragment seq) =
        AttrRenderFragment(fun comp builder index -> (nodes |> Seq.fold (>=>) emptyNode).Invoke(comp, builder, index))

    member inline _.childContent(x: string) =
        AttrRenderFragment(fun comp builder index -> (html.text x).Invoke(comp, builder, index))
    
    member inline _.childContent(x: int) =
        AttrRenderFragment(fun comp builder index -> (html.text x).Invoke(comp, builder, index))
    
    member inline _.childContent(x: float) =
        AttrRenderFragment(fun comp builder index -> (html.text x).Invoke(comp, builder, index))

    member inline _.styles x = html.styles x

    member inline _.value x = "value" => x

    member inline _.onfocus callback = html.callback("onfocus", callback)
    member inline _.onfocus callback = html.callbackTask("onfocus", callback)
    member inline _.onblur callback = html.callback("onblur", callback)
    member inline _.onblur callback = html.callbackTask("onblur", callback)
    member inline _.onfocusin callback = html.callback("onfocusin", callback)
    member inline _.onfocusin callback = html.callbackTask("onfocusin", callback)
    member inline _.onfocusout callback = html.callback("onfocusout", callback)
    member inline _.onfocusout callback = html.callbackTask("onfocusout", callback)
    member inline _.onmouseover callback = html.callback("onmouseover", callback)
    member inline _.onmouseover callback = html.callbackTask("onmouseover", callback)
    member inline _.onmouseout callback = html.callback("onmouseout", callback)
    member inline _.onmouseout callback = html.callbackTask("onmouseout", callback)
    member inline _.onmousemove callback = html.callback("onmousemove", callback)
    member inline _.onmousemove callback = html.callbackTask("onmousemove", callback)
    member inline _.onmousedown callback = html.callback("onmousedown", callback)
    member inline _.onmousedown callback = html.callbackTask("onmousedown", callback)
    member inline _.onmouseup callback = html.callback("onmouseup", callback)
    member inline _.onmouseup callback = html.callbackTask("onmouseup", callback)
    member inline _.onclick callback = html.callback("onclick", callback)
    member inline _.onclick callback = html.callbackTask("onclick", callback)
    member inline _.ondblclick callback = html.callback("ondblclick", callback)
    member inline _.ondblclick callback = html.callbackTask("ondblclick", callback)
    member inline _.onwheel callback = html.callback("onwheel", callback)
    member inline _.onwheel callback = html.callbackTask("onwheel", callback)
    member inline _.onmousewheel callback = html.callback("onmousewheel", callback)
    member inline _.onmousewheel callback = html.callbackTask("onmousewheel", callback)
    member inline _.oncontextmenu callback = html.callback("oncontextmenu", callback)
    member inline _.oncontextmenu callback = html.callbackTask("oncontextmenu", callback)
    member inline _.ondrag callback = html.callback("ondrag", callback)
    member inline _.ondrag callback = html.callbackTask("ondrag", callback)
    member inline _.ondragend callback = html.callback("ondragend", callback)
    member inline _.ondragend callback = html.callbackTask("ondragend", callback)
    member inline _.ondragenter callback = html.callback("ondragenter", callback)
    member inline _.ondragenter callback = html.callbackTask("ondragenter", callback)
    member inline _.ondragleave callback = html.callback("ondragleave", callback)
    member inline _.ondragleave callback = html.callbackTask("ondragleave", callback)
    member inline _.ondragover callback = html.callback("ondragover", callback)
    member inline _.ondragover callback = html.callbackTask("ondragover", callback)
    member inline _.ondragstart callback = html.callback("ondragstart", callback)
    member inline _.ondragstart callback = html.callbackTask("ondragstart", callback)
    member inline _.ondrop callback = html.callback("ondrop", callback)
    member inline _.ondrop callback = html.callbackTask("ondrop", callback)
    member inline _.onkeydown callback = html.callback("onkeydown", callback)
    member inline _.onkeydown callback = html.callbackTask("onkeydown", callback)
    member inline _.onkeyup callback = html.callback("onkeyup", callback)
    member inline _.onkeyup callback = html.callbackTask("onkeyup", callback)
    member inline _.onkeypress callback = html.callback("onkeypress", callback)
    member inline _.onkeypress callback = html.callbackTask("onkeypress", callback)
    member inline _.onchange callback = html.callback("onchange", callback)
    member inline _.onchange callback = html.callbackTask("onchange", callback)
    member inline _.oninput callback = html.callback("oninput", callback)
    member inline _.oninput callback = html.callbackTask("oninput", callback)
    member inline _.oninvalid callback = html.callback("oninvalid", callback)
    member inline _.oninvalid callback = html.callbackTask("oninvalid", callback)
    member inline _.onreset callback = html.callback("onreset", callback)
    member inline _.onreset callback = html.callbackTask("onreset", callback)
    member inline _.onselect callback = html.callback("onselect", callback)
    member inline _.onselect callback = html.callbackTask("onselect", callback)
    member inline _.onselectstart callback = html.callback("onselectstart", callback)
    member inline _.onselectstart callback = html.callbackTask("onselectstart", callback)
    member inline _.onselectionchange callback = html.callback("onselectionchange", callback)
    member inline _.onselectionchange callback = html.callbackTask("onselectionchange", callback)
    member inline _.onsubmit callback = html.callback("onsubmit", callback)
    member inline _.onsubmit callback = html.callbackTask("onsubmit", callback)
    member inline _.onbeforecopy callback = html.callback("onbeforecopy", callback)
    member inline _.onbeforecopy callback = html.callbackTask("onbeforecopy", callback)
    member inline _.onbeforecut callback = html.callback("onbeforecut", callback)
    member inline _.onbeforecut callback = html.callbackTask("onbeforecut", callback)
    member inline _.onbeforepaste callback = html.callback("onbeforepaste", callback)
    member inline _.onbeforepaste callback = html.callbackTask("onbeforepaste", callback)
    member inline _.oncopy callback = html.callback("oncopy", callback)
    member inline _.oncopy callback = html.callbackTask("oncopy", callback)
    member inline _.oncut callback = html.callback("oncut", callback)
    member inline _.oncut callback = html.callbackTask("oncut", callback)
    member inline _.onpaste callback = html.callback("onpaste", callback)
    member inline _.onpaste callback = html.callbackTask("onpaste", callback)
    member inline _.ontouchcancel callback = html.callback("ontouchcancel", callback)
    member inline _.ontouchcancel callback = html.callbackTask("ontouchcancel", callback)
    member inline _.ontouchend callback = html.callback("ontouchend", callback)
    member inline _.ontouchend callback = html.callbackTask("ontouchend", callback)
    member inline _.ontouchmove callback = html.callback("ontouchmove", callback)
    member inline _.ontouchmove callback = html.callbackTask("ontouchmove", callback)
    member inline _.ontouchstart callback = html.callback("ontouchstart", callback)
    member inline _.ontouchstart callback = html.callbackTask("ontouchstart", callback)
    member inline _.ontouchenter callback = html.callback("ontouchenter", callback)
    member inline _.ontouchenter callback = html.callbackTask("ontouchenter", callback)
    member inline _.ontouchleave callback = html.callback("ontouchleave", callback)
    member inline _.ontouchleave callback = html.callbackTask("ontouchleave", callback)
    member inline _.onpointercapture callback = html.callback("onpointercapture", callback)
    member inline _.onpointercapture callback = html.callbackTask("onpointercapture", callback)
    member inline _.onlostpointercapture callback = html.callback("onlostpointercapture", callback)
    member inline _.onlostpointercapture callback = html.callbackTask("onlostpointercapture", callback)
    member inline _.onpointercancel callback = html.callback("onpointercancel", callback)
    member inline _.onpointercancel callback = html.callbackTask("onpointercancel", callback)
    member inline _.onpointerdown callback = html.callback("onpointerdown", callback)
    member inline _.onpointerdown callback = html.callbackTask("onpointerdown", callback)
    member inline _.onpointerenter callback = html.callback("onpointerenter", callback)
    member inline _.onpointerenter callback = html.callbackTask("onpointerenter", callback)
    member inline _.onpointerleave callback = html.callback("onpointerleave", callback)
    member inline _.onpointerleave callback = html.callbackTask("onpointerleave", callback)
    member inline _.onpointermove callback = html.callback("onpointermove", callback)
    member inline _.onpointermove callback = html.callbackTask("onpointermove", callback)
    member inline _.onpointerout callback = html.callback("onpointerout", callback)
    member inline _.onpointerout callback = html.callbackTask("onpointerout", callback)
    member inline _.onpointerover callback = html.callback("onpointerover", callback)
    member inline _.onpointerover callback = html.callbackTask("onpointerover", callback)
    member inline _.onpointerup callback = html.callback("onpointerup", callback)
    member inline _.onpointerup callback = html.callbackTask("onpointerup", callback)
    member inline _.oncanplay callback = html.callback("oncanplay", callback)
    member inline _.oncanplay callback = html.callbackTask("oncanplay", callback)
    member inline _.oncanplaythrough callback = html.callback("oncanplaythrough", callback)
    member inline _.oncanplaythrough callback = html.callbackTask("oncanplaythrough", callback)
    member inline _.oncuechange callback = html.callback("oncuechange", callback)
    member inline _.oncuechange callback = html.callbackTask("oncuechange", callback)
    member inline _.ondurationchange callback = html.callback("ondurationchange", callback)
    member inline _.ondurationchange callback = html.callbackTask("ondurationchange", callback)
    member inline _.onemptied callback = html.callback("onemptied", callback)
    member inline _.onemptied callback = html.callbackTask("onemptied", callback)
    member inline _.onpause callback = html.callback("onpause", callback)
    member inline _.onpause callback = html.callbackTask("onpause", callback)
    member inline _.onplay callback = html.callback("onplay", callback)
    member inline _.onplay callback = html.callbackTask("onplay", callback)
    member inline _.onplaying callback = html.callback("onplaying", callback)
    member inline _.onplaying callback = html.callbackTask("onplaying", callback)
    member inline _.onratechange callback = html.callback("onratechange", callback)
    member inline _.onratechange callback = html.callbackTask("onratechange", callback)
    member inline _.onseeked callback = html.callback("onseeked", callback)
    member inline _.onseeked callback = html.callbackTask("onseeked", callback)
    member inline _.onseeking callback = html.callback("onseeking", callback)
    member inline _.onseeking callback = html.callbackTask("onseeking", callback)
    member inline _.onstalled callback = html.callback("onstalled", callback)
    member inline _.onstalled callback = html.callbackTask("onstalled", callback)
    member inline _.onstop callback = html.callback("onstop", callback)
    member inline _.onstop callback = html.callbackTask("onstop", callback)
    member inline _.onsuspend callback = html.callback("onsuspend", callback)
    member inline _.onsuspend callback = html.callbackTask("onsuspend", callback)
    member inline _.ontimeupdate callback = html.callback("ontimeupdate", callback)
    member inline _.ontimeupdate callback = html.callbackTask("ontimeupdate", callback)
    member inline _.onvolumechange callback = html.callback("onvolumechange", callback)
    member inline _.onvolumechange callback = html.callbackTask("onvolumechange", callback)
    member inline _.onwaiting callback = html.callback("onwaiting", callback)
    member inline _.onwaiting callback = html.callbackTask("onwaiting", callback)
    member inline _.onloadstart callback = html.callback("onloadstart", callback)
    member inline _.onloadstart callback = html.callbackTask("onloadstart", callback)
    member inline _.ontimeout callback = html.callback("ontimeout", callback)
    member inline _.ontimeout callback = html.callbackTask("ontimeout", callback)
    member inline _.onabort callback = html.callback("onabort", callback)
    member inline _.onabort callback = html.callbackTask("onabort", callback)
    member inline _.onload callback = html.callback("onload", callback)
    member inline _.onload callback = html.callbackTask("onload", callback)
    member inline _.onloadend callback = html.callback("onloadend", callback)
    member inline _.onloadend callback = html.callbackTask("onloadend", callback)
    member inline _.onprogress callback = html.callback("onprogress", callback)
    member inline _.onprogress callback = html.callbackTask("onprogress", callback)
    member inline _.onerror callback = html.callback("onerror", callback)
    member inline _.onerror callback = html.callbackTask("onerror", callback)
    member inline _.onactivate callback = html.callback("onactivate", callback)
    member inline _.onactivate callback = html.callbackTask("onactivate", callback)
    member inline _.onbeforeactivate callback = html.callback("onbeforeactivate", callback)
    member inline _.onbeforeactivate callback = html.callbackTask("onbeforeactivate", callback)
    member inline _.onbeforedeactivate callback = html.callback("onbeforedeactivate", callback)
    member inline _.onbeforedeactivate callback = html.callbackTask("onbeforedeactivate", callback)
    member inline _.ondeactivate callback = html.callback("ondeactivate", callback)
    member inline _.ondeactivate callback = html.callbackTask("ondeactivate", callback)
    member inline _.onended callback = html.callback("onended", callback)
    member inline _.onended callback = html.callbackTask("onended", callback)
    member inline _.onfullscreenchange callback = html.callback("onfullscreenchange", callback)
    member inline _.onfullscreenchange callback = html.callbackTask("onfullscreenchange", callback)
    member inline _.onfullscreenerror callback = html.callback("onfullscreenerror", callback)
    member inline _.onfullscreenerror callback = html.callbackTask("onfullscreenerror", callback)
    member inline _.onloadeddata callback = html.callback("onloadeddata", callback)
    member inline _.onloadeddata callback = html.callbackTask("onloadeddata", callback)
    member inline _.onloadedmetadata callback = html.callback("onloadedmetadata", callback)
    member inline _.onloadedmetadata callback = html.callbackTask("onloadedmetadata", callback)
    member inline _.onpointerlockchange callback = html.callback("onpointerlockchange", callback)
    member inline _.onpointerlockchange callback = html.callbackTask("onpointerlockchange", callback)
    member inline _.onpointerlockerror callback = html.callback("onpointerlockerror", callback)
    member inline _.onpointerlockerror callback = html.callbackTask("onpointerlockerror", callback)
    member inline _.onreadystatechange callback = html.callback("onreadystatechange", callback)
    member inline _.onreadystatechange callback = html.callbackTask("onreadystatechange", callback)
    member inline _.onscroll callback = html.callback("onscroll", callback)
    member inline _.onscroll callback = html.callbackTask("onscroll", callback)
