[<AutoOpen>]
module Fun.Blazor.DslElmish

open Elmish
open Operators


type html with

    /// init will be called OnInitialized, but the cmd generated by init will not be exec to avoid server mode blazor prerender loop issue
    /// After first render, elmish loop will exec cmd created by init. And continue with its state.
    static member elmish
        (
            init: unit -> 'State * Cmd<'Msg>,
            update: 'Msg -> 'State -> 'State * Cmd<'Msg>,
            view: 'State -> Dispatch<'Msg> -> NodeRenderFragment
        )
        =
        ComponentWithChildBuilder<ElmComponent<'State, 'Msg>>(){
            "Init" => init
            "Update" => update
            "View" => view
        }


    static member elmish
        (
            initState: unit -> 'State,
            updateState: 'Msg -> 'State -> 'State,
            render: 'State -> Dispatch<'Msg> -> NodeRenderFragment
        )
        =
        html.elmish ((fun () -> initState (), Cmd.none), (fun msg state -> updateState msg state, Cmd.none), render)
